# Generated by Django 2.0.13 on 2019-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('heartrate', models.PositiveIntegerField()),
                ('type', models.PositiveIntegerField()),
            ],
        ),
    ]
