# Generated by Django 2.2.7 on 2019-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoursleeping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='heartrate',
        ),
        migrations.AddField(
            model_name='activity',
            name='heart_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='sleep_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.PositiveIntegerField(default=19700101),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
